version: '3.8'

services:
  node-app:
    build: .
    image: node-app
    environment:
        DATABASE_URL: mongodb://mongodb:27017/bankdatabase
        PORT: 3002
    ports:
      - 3002:3002
    depends_on:
      - mongodb
    volumes:
      - .:/user/src/app
    networks:
      - node-network

  mongodb:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongodb:/data/db
    networks:
      - node-network

volumes:
  mongodb:

networks:
  node-network:
    driver: bridge